### ISSUE TITLE
Prompts for BoardgameQA

### ISSUE THREAD

**Issue by HaritzPuerto** [xiye17/SAT-LM#1]
Hello!

This is a very interesting work! I enjoyed reading your paper! 

I was wondering whether it would be possible to release the prompts for boardgameqa too?

Thanks!

**Comment by xiye17** [comment]
Hi, I just updated the data/prompts/ and code-002-cache for boadgameqa dataset. I also updated the READMe accordingly.

**Comment by HaritzPuerto** [comment]
thank you!
