### ISSUE TITLE
Regarding reproduction of results

### ISSUE THREAD

**Issue by abhinandan12345678** [xiye17/SAT-LM#3]
I read the paper and got interested and ran the code.
but all the models are currently deprecated.
Can anyone help me out about what to do to reproduce?

**Comment by xiye17** [comment]
Thanks for the comment. GPT instruct series models have been deprecated since Jan 2024. You may want to add support to gpt-3.5 / or gpt-4 by modifying some of the api-query related code.

**Comment by abhinandan12345678** [comment]
Okay..thanks

**Comment by abhinandan12345678** [comment]
Done
